---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: earthquake-wrk-deployment
  labels:
    app: earthquake-wrk
spec:
  replicas: 2
  selector:
    matchLabels:
      app: earthquake-wrk
  template:
    metadata:
      labels:
        app: earthquake-wrk
    spec:
      containers:
        - name: earthquake-wrk
          imagePullPolicy: Always
          image: serenashah/earthquake-wrk:0.1
          env:
          - name: REDIS_IP
            value: "10.109.228.201"